server:
  port: 1000
spring:
  application:
    name: producer-app
  datasource:
    url: jdbc:mysql://localhost:3306/stock_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
  boot:
    admin:
      client:
        url: http://localhost:1002/
  
logging:
  level:
    com.producer.demo: DEBUG
eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true


info:
  application: 
    name: Investors and stock
    version: V1.0
    desc: This will show the details of stock and investors
     
management:
  server:
    port: 1000
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    health:
      show-details: always
  
  
